// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	routes "github.com/gothicframework/core/router"
	"net/http"
)

/**
 * `LazyLoadProps` defines the props passed to the `LazyLoad` component.
 *
 * It is a simple boolean value:
 * - `true` indicates the initial (placeholder) render — usually triggered from a full page render.
 * - `false` indicates the second load — when HTMX fetches the full content.
 */
type LazyLoadProps = bool

/**
 * `LazyLoadConfig` sets up a static route for the lazy-loaded component.
 *
 * - `Type`: Set to `STATIC` so responses can be cached by CDNs like CloudFront.
 * - `HttpMethod`: Uses `GET`, which aligns with HTMX's default behavior for fetching content.
 * - `Middleware`: In this case, always returns `false` — because it is only called via HTMX
 *   after the initial placeholder render, meaning this is *not* the first load.
 *
 * Note: The first render with `true` should be triggered from a parent component or page.
 */
var LazyLoadConfig = routes.RouteConfig[LazyLoadProps]{
	Type:       routes.STATIC,
	HttpMethod: routes.GET,
	Middleware: func(w http.ResponseWriter, r *http.Request) LazyLoadProps {
		// HTMX-triggered follow-up calls always treat this as a non-initial render
		return false
	},
}

/**
 *                         ⚡ Component Lazy Loading
 *
 * `LazyLoad` is a reusable pattern for lazy-loading components to improve performance
 * and SEO by reducing initial page size and deferring content until it’s needed.
 *
 * How it works:
 * - When `isFirstLoad` is `true` (set by the parent page/component):
 *   - Renders a skeleton or placeholder.
 *   - Uses `hx-get` to trigger an HTMX request for the actual component.
 *   - When the request completes, the placeholder is swapped with the real content.
 *
 * - When `isFirstLoad` is `false` (HTMX has loaded the route):
 *   - The actual content is rendered directly.
 *
 * Tip: Use this component to load large or non-critical UI parts *after* the initial page render.
 */

func LazyLoad(isFirstLoad LazyLoadProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if isFirstLoad {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div hx-get=\"/yourLazyLoadedComponent\" hx-trigger=\"load\" hx-swap=\"outerHTML\"><div>Put your skeleton loader or placeholder here for `/yourLazyLoadedComponent`</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div>This is the actual content loaded after the placeholder</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
