// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/felipegenef/gothicframework/v2/pkg/helpers/routes"

var _ = routes.RouteConfig{}

var _ = templruntime.GeneratedTemplate
