package cmd

import (
	"os"
	"path/filepath"

	gothic_cli "github.com/gothicframework/cli/v3/internal/cli"
	gothic_config "github.com/gothicframework/core/config"
)

// gothicEmbedFileName is the root `package main` file that bakes ./public into the
// server binary. It MUST live at the project root (next to the generated main.go),
// NOT under src/routes: //go:embed cannot reference a parent directory ("..").
const gothicEmbedFileName = "gothic_embed.go"

// gothicEmbedTemplate is the exact, locked content of the generated embed file.
// `all:public` embeds dot/underscore files too, matching the disk file server.
const gothicEmbedTemplate = `// Code generated by gothic. DO NOT EDIT.
// Generated only when Runtime.ServeStaticFiles is EMBEDDED. Bakes ./public into the binary
// for a single self-contained server. Removed automatically when you switch away from EMBEDDED.
package main

import (
	"embed"
	"io/fs"

	"github.com/gothicframework/middlewares"
)

//go:embed all:public
var gothicEmbeddedPublic embed.FS

func init() {
	sub, err := fs.Sub(gothicEmbeddedPublic, "public")
	if err != nil {
		panic("gothic: embedding public folder: " + err.Error())
	}
	middlewares.SetEmbeddedPublicFS(sub)
}
`

// syncEmbeddedPublicFile keeps ./gothic_embed.go in sync with the configured
// static-files mode. When Runtime.ServeStaticFiles is EMBEDDED it ensures a
// non-empty ./public exists (a .gitkeep guarantees //go:embed all:public compiles)
// and writes the embed file; for every other mode it removes a stale embed file so
// opting out never leaves ./public baked into (and bloating) the binary. Writing
// the identical bytes on repeat runs is intentional and idempotent.
func syncEmbeddedPublicFile(cfg *gothic_cli.Config) error {
	if cfg == nil || cfg.Runtime.ServeStaticFiles != gothic_config.EMBEDDED {
		if err := os.Remove(gothicEmbedFileName); err != nil && !os.IsNotExist(err) {
			return err
		}
		return nil
	}

	if err := os.MkdirAll("public", 0o755); err != nil {
		return err
	}
	// //go:embed all:public fails to compile when ./public is empty. A committed
	// .gitkeep guarantees at least one entry.
	gitkeep := filepath.Join("public", ".gitkeep")
	if _, err := os.Stat(gitkeep); os.IsNotExist(err) {
		if err := os.WriteFile(gitkeep, nil, 0o644); err != nil {
			return err
		}
	} else if err != nil {
		return err
	}

	return os.WriteFile(gothicEmbedFileName, []byte(gothicEmbedTemplate), 0o644)
}

// embeddedOnAWSWarning returns a user-facing warning when a config using the
// EMBEDDED static-files mode is deployed to AWS — where /public/* is served by
// CloudFront/S3, so embedding the public folder only bloats the Lambda. It returns
// "" when no warning applies. Kept as a pure helper so it is testable without
// capturing stdout, and so the deploy path only decides where to print it.
func embeddedOnAWSWarning(cfg *gothic_cli.Config) string {
	if cfg == nil || cfg.Runtime.ServeStaticFiles != gothic_config.EMBEDDED {
		return ""
	}
	return "EMBEDDED is optimized for self-hosted single-binary deploys; on AWS " +
		"/public/* is served by CloudFront/S3, so embedding only bloats the Lambda. " +
		"Consider CDN for AWS."
}
