// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/gothicframework/components"
	routes "github.com/gothicframework/core/router"
	"net/http"
	"{{.GoModName}}/src/components"
	"{{.GoModName}}/src/layouts"
)

/**
 * Define the type of props your page or component will receive.
 *
 * This type must remain consistent across:
 * - `RouteConfig` (used to configure the route)
 * - `Middleware` (which injects the props)
 * - The page/component itself (as the props input)
 *
 * In this example, `IndexPageProps` is an empty interface, but you can define any structure that fits your needs.
 */
type IndexPageProps = interface{}

/**
 * `IndexConfig` describes how this specific page should behave within the Gothic routing system.
 *
 * Options include:
 * - `Type`: Controls how the page is rendered:
 *     - `STATIC` (default): Renders once and is cached.
 *     - `DYNAMIC`: Runs middleware on every request.
 *     - `ISR`: Regenerates at intervals you define (good for SEO + performance).
 *
 * - `HttpMethod`: Optionally define the HTTP method for HTMX to fetch this page (`GET`, `POST`, etc.).
 *
 * - `Middleware`: A function that receives the request and returns props for the page/component.
 *   - For `STATIC`, runs once on first request.
 *   - For `DYNAMIC`, runs on every request.
 *   - For `ISR`, runs at the interval specified by `RevalidateInSec`.
 *
 * Cache backend is configured in `main.go` via `gothicRoutes.Setup()`:
 *   - `CacheStrategy`: `CACHE_CONTROL_HEADERS` (default), `IN_MEMORY`, `REDIS`, or `LOCAL_FILES`.
 *   - `CacheConfig.RedisURL` / `CacheConfig.RedisPassword`: Required for `REDIS`.
 *   - `CacheConfig.CacheFilesPath`: Directory for `LOCAL_FILES` (default: `.gothic-cache`).
 *   - `CacheConfig.Compression` / `CacheConfig.CompressionMethod`: Enable gzip or brotli compression.
 */
var IndexConfig = routes.RouteConfig[IndexPageProps]{
	Type:       routes.STATIC,
	HttpMethod: routes.GET,
	Middleware: func(w http.ResponseWriter, r *http.Request) IndexPageProps {
		return nil
	},
}

func Index(props IndexPageProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"sm:w-[300px] sm:h-[300px] w-[200px] h-[200px] my-10 rounded-full animate-pulse overflow-clip\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = gothicComponents.OptimizedImage(gothicComponents.OptimizedImageProps{IsFirstLoad: true, ImgName: "imageExample", ImgExtension: "png", Alt: "Gothic Framework Logo"}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = components.HelloWorld(nil).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <div class=\"flex flex-col justify-center items-center max-w-xl text-center\"><p class=\"font-normal text-gray-400 text-base sm:text-xl\">Do you want to build <span class=\"font-semibold text-white\">Modern Web Apps</span> with the <span class=\"font-bold text-cyan-400 text-lg sm:text-2xl\">Go</span> programing language as easy as if it was <span class=\"font-bold text-yellow-400 text-base sm:text-xl\">Javascript</span>?</p><a target=\"_blank\" class=\"font-bold text-black text-base sm:text-xl py-4 px-6 sm:px-10 bg-pink-500 hover:bg-pink-300 mt-20 rounded-md\" href=\"https://gothicframework.com\">See our docs</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.PageLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
