// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	routes "github.com/gothicframework/core/router"
	"net/http"
	"time"
	"{{.GoModName}}/src/layouts"
)

/**
 * `RevalidateProps` defines the data (props) that this page receives from the middleware.
 * In this case, we’re passing a `time.Time` value that will be displayed in the page.
 */
type RevalidateProps = time.Time

/**
 * `RevalidateConfig` defines the configuration for this ISR-enabled route.
 *
 * - `Type`: Set to `ISR` (Incremental Static Regeneration), allowing the page to be statically generated
 *   and then revalidated in the background every `RevalidateInSec` seconds.
 * - `HttpMethod`: Sets the HTTP method this page responds to (in this case, GET).
 * - `Middleware`: Runs server-side to generate the props (`RevalidateProps`) for the page.
 * - `RevalidateInSec`: Specifies the revalidation interval in seconds (every 10 seconds).
 *
 * Cache backend is configured in main.go via gothicRoutes.Setup().
 * Default: CACHE_CONTROL_HEADERS in production, in-memory during development (hot-reload).
 */
var RevalidateConfig = routes.RouteConfig[RevalidateProps]{
	Type:       routes.ISR,
	HttpMethod: routes.GET,
	Middleware: func(w http.ResponseWriter, r *http.Request) RevalidateProps {
		return time.Now()
	},
	RevalidateInSec: 10, // Revalidate this page every 10 seconds
}

/**
 * `Revalidate` is the actual page component, rendered with the props returned by the middleware.
 *
 * The current server time is displayed in RFC3339 format, showcasing that the page updates at intervals.
 */

func Revalidate(currentTime RevalidateProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col justify-center items-center w-screen h-screen\"><h1 class=\"text-4xl mb-5 text-white\">ISR Feature with GOTH APP</h1><span class=\"font-bold text-white\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(currentTime.Format(time.RFC3339))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/scaffold/src/pages/revalidate.templ`, Line: 47, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.PageLayout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
